# Generated by Django 5.0.1 on 2026-08-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('surgery_type', models.CharField(max_length=100, verbose_name='手术类型')),
                ('surgery_date', models.DateField(blank=True, null=True, verbose_name='手术日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
                'db_table': 'patients',
            },
        ),
    ]
