# Generated by Django 5.0.1 on 2026-08-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_card',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号'),
        ),
    ]
