# Generated by Django 5.0.1 on 2026-08-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('approved', '已绑定'), ('rejected', '已拒绝'), ('unbound', '已解除')], default='pending', max_length=10, verbose_name='绑定状态')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '医患绑定',
                'verbose_name_plural': '医患绑定',
                'db_table': 'bindings',
            },
        ),
    ]
