# Generated by Django 5.0.1 on 2026-08-09 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bindings', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binding',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='patients.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='binding',
            unique_together={('doctor', 'patient')},
        ),
    ]
