# Generated by Django 5.0.1 on 2026-08-09 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('content', models.TextField(verbose_name='任务内容')),
                ('task_types', models.JSONField(default=list, verbose_name='任务类型')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '待完成'), ('completed', '已完成')], default='not_started', max_length=15, verbose_name='任务状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='patients.patient')),
            ],
            options={
                'verbose_name': '随访任务',
                'verbose_name_plural': '随访任务',
                'db_table': 'followup_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='提交内容')),
                ('images', models.JSONField(default=list, verbose_name='图片附件')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.followuptask')),
            ],
            options={
                'verbose_name': '任务提交',
                'verbose_name_plural': '任务提交',
                'db_table': 'task_submissions',
            },
        ),
    ]
