# Generated by Django 5.0.1 on 2026-08-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followuptask',
            options={'ordering': ['-created_at'], 'verbose_name': '随���任务', 'verbose_name_plural': '随���任务'},
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='content',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='备注���明'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='submission_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='���交数据'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='content',
            field=models.TextField(verbose_name='任���内���'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时���'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='deadline',
            field=models.DateTimeField(verbose_name='截止时���'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='status',
            field=models.CharField(choices=[('not_started', '未开始'), ('in_progress', '待完成'), ('completed', '已完成')], default='not_started', max_length=15, verbose_name='任务���态'),
        ),
        migrations.AlterField(
            model_name='followuptask',
            name='title',
            field=models.CharField(max_length=200, verbose_name='任务标���'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='图片���件'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='���交���间'),
        ),
    ]
