# Generated by Django 5.0.1 on 2026-08-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('hospital', models.CharField(max_length=100, verbose_name='医院')),
                ('department', models.CharField(max_length=50, verbose_name='科室')),
                ('title', models.CharField(choices=[('chief', '主任医师'), ('associate_chief', '副主任医师'), ('attending', '主治医师'), ('resident', '住院医师')], max_length=20, verbose_name='职称')),
                ('audit_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '医生',
                'verbose_name_plural': '医生',
                'db_table': 'doctors',
            },
        ),
    ]
